name: GMDSaveExplorer Compiler
run-name: Compile GMDSaveExplorer
on: [push]
jobs:
  Compile:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Get App Version
        id: version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: package.json
          prop_path: version

      - name: Install Packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./dist/SaveExplorer.exe
          tag_name: v${{ steps.version.outputs.prop }}
          prerelease: true